---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torn-market-capture-data
  namespace: default
  labels:
    app: torn-market-capture
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
